// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "alert": {
      name: "alert",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/default/ui/alert")),
      source: "",
      files: ["registry/default/ui/alert.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "alert-dialog": {
      name: "alert-dialog",
      type: "components:ui",
      registryDependencies: ["button"],
      component: React.lazy(() => import("@/registry/default/ui/alert-dialog")),
      source: "",
      files: ["registry/default/ui/alert-dialog.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "avatar": {
      name: "avatar",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/default/ui/avatar")),
      source: "",
      files: ["registry/default/ui/avatar.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "button": {
      name: "button",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/default/ui/button")),
      source: "",
      files: ["registry/default/ui/button.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "dialog": {
      name: "dialog",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/default/ui/dialog")),
      source: "",
      files: ["registry/default/ui/dialog.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "dropdown-menu": {
      name: "dropdown-menu",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/default/ui/dropdown-menu")),
      source: "",
      files: ["registry/default/ui/dropdown-menu.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "input": {
      name: "input",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/default/ui/input")),
      source: "",
      files: ["registry/default/ui/input.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "label": {
      name: "label",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/default/ui/label")),
      source: "",
      files: ["registry/default/ui/label.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "navigation-menu": {
      name: "navigation-menu",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/default/ui/navigation-menu")),
      source: "",
      files: ["registry/default/ui/navigation-menu.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "popover": {
      name: "popover",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/default/ui/popover")),
      source: "",
      files: ["registry/default/ui/popover.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "textarea": {
      name: "textarea",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/default/ui/textarea")),
      source: "",
      files: ["registry/default/ui/textarea.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
  },
}
